import { useEffect, useMemo, useRef, useState, useCallback } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

/**
 * Fretboard — a real, playable guitar built with WebAudio.
 *
 * Audio:
 *   Karplus-Strong plucked-string synthesis. Each note is generated by seeding
 *   a circular buffer with white noise then averaging adjacent samples one
 *   period back, with a small decay. Sounds far more "guitar" than a sine wave.
 *
 * Strings (top to bottom in the UI = high to low):
 *   E4 / B3 / G3 / D3 / A2 / E2  (standard tuning)
 *
 * Modes:
 *   • Free play — click any fret to play it.
 *   • Chord shapes — C, G, D, Am, Em, F. Click "Strum" or hit Space.
 *   • Note quiz — name the highlighted note before the timer runs out.
 */

const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

// Strings top-to-bottom: high E first.
const STRINGS = [
  { label: 'E', baseFreq: 329.63, midi: 64 }, // 1st string, high E
  { label: 'B', baseFreq: 246.94, midi: 59 },
  { label: 'G', baseFreq: 196.00, midi: 55 },
  { label: 'D', baseFreq: 146.83, midi: 50 },
  { label: 'A', baseFreq: 110.00, midi: 45 },
  { label: 'E', baseFreq: 82.41,  midi: 40 }, // 6th string, low E
];

const FRETS = 12;

// Chord shapes — frets per string, top-to-bottom (high E first). null = muted, 0 = open.
const CHORDS = {
  C:  { name: 'C major',  shape: [0, 1, 0, 2, 3, null] },
  G:  { name: 'G major',  shape: [3, 0, 0, 0, 2, 3]    },
  D:  { name: 'D major',  shape: [2, 3, 2, 0, null, null] },
  Am: { name: 'A minor',  shape: [0, 1, 2, 2, 0, null] },
  Em: { name: 'E minor',  shape: [0, 0, 0, 2, 2, 0]    },
  F:  { name: 'F major',  shape: [1, 1, 2, 3, 3, 1]    },
};

function noteAt(stringIdx, fret) {
  const midi = STRINGS[stringIdx].midi + fret;
  const name = NOTE_NAMES[midi % 12];
  const octave = Math.floor(midi / 12) - 1;
  return { name, octave, midi };
}

function freqAt(stringIdx, fret) {
  return STRINGS[stringIdx].baseFreq * Math.pow(2, fret / 12);
}

// ---------------- Karplus-Strong audio engine ----------------
function useGuitarAudio() {
  const ctxRef = useRef(null);
  const masterRef = useRef(null);

  const ensure = useCallback(() => {
    if (!ctxRef.current) {
      const Ctx = window.AudioContext || window.webkitAudioContext;
      if (!Ctx) return null;
      const ctx = new Ctx();
      const master = ctx.createGain();
      master.gain.value = 0.45;
      master.connect(ctx.destination);
      ctxRef.current = ctx;
      masterRef.current = master;
    }
    if (ctxRef.current.state === 'suspended') ctxRef.current.resume();
    return ctxRef.current;
  }, []);

  const pluck = useCallback((freq, { duration = 1.6, gain = 1, decay = 0.996 } = {}) => {
    const ctx = ensure();
    if (!ctx) return;
    const sr = ctx.sampleRate;
    const period = Math.max(2, Math.round(sr / freq));
    const length = Math.floor(sr * duration);
    const buf = ctx.createBuffer(1, length, sr);
    const data = buf.getChannelData(0);
    // 1) noise burst, lightly low-passed to soften brightness
    let prev = 0;
    for (let i = 0; i < period; i++) {
      const n = Math.random() * 2 - 1;
      const lp = 0.5 * (n + prev);
      data[i] = lp;
      prev = n;
    }
    // 2) Karplus-Strong delay loop with averaging + decay
    for (let i = period; i < length; i++) {
      data[i] = decay * 0.5 * (data[i - period] + data[i - period + 1]);
    }
    const src = ctx.createBufferSource();
    src.buffer = buf;
    const g = ctx.createGain();
    g.gain.setValueAtTime(gain, ctx.currentTime);
    g.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + duration);
    src.connect(g).connect(masterRef.current);
    src.start();
    src.stop(ctx.currentTime + duration);
  }, [ensure]);

  return { pluck, ensure };
}

// ---------------- Visual fretboard ----------------
export default function Fretboard() {
  const sectionRef = useRef(null);
  const [mode, setMode] = useState('free'); // 'free' | 'chord' | 'quiz'
  const [activeChord, setActiveChord] = useState('G');
  const [ringing, setRinging] = useState({}); // key `${s}-${f}` -> timestamp
  const { pluck, ensure } = useGuitarAudio();

  // ---- play helpers ----
  const playNote = useCallback((stringIdx, fret) => {
    pluck(freqAt(stringIdx, fret), {
      // Bass strings sustain longer / quieter; treble strings ring brighter.
      duration: 1.2 + (5 - stringIdx) * 0.18,
      gain: 0.9 - stringIdx * 0.06,
      decay: 0.994 + stringIdx * 0.0008,
    });
    const key = `${stringIdx}-${fret}`;
    setRinging((r) => ({ ...r, [key]: Date.now() }));
    setTimeout(() => {
      setRinging((r) => {
        const c = { ...r };
        delete c[key];
        return c;
      });
    }, 700);
  }, [pluck]);

  const strum = useCallback((shape) => {
    ensure();
    // strum from low (6th string) to high (1st string), small delay between
    const order = [5, 4, 3, 2, 1, 0];
    order.forEach((s, i) => {
      const fret = shape[s];
      if (fret == null) return; // muted
      setTimeout(() => playNote(s, fret), i * 35);
    });
  }, [ensure, playNote]);

  // ---- keyboard: Space = strum current chord ----
  useEffect(() => {
    const onKey = (e) => {
      if (e.code === 'Space' && mode === 'chord') {
        e.preventDefault();
        strum(CHORDS[activeChord].shape);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [mode, activeChord, strum]);

  // ---- quiz state ----
  const [quizTarget, setQuizTarget] = useState(null); // {string, fret, note}
  const [quizScore, setQuizScore] = useState(0);
  const [quizStreak, setQuizStreak] = useState(0);
  const [quizFeedback, setQuizFeedback] = useState(null); // 'right' | 'wrong' | null

  const newQuiz = useCallback(() => {
    const stringIdx = Math.floor(Math.random() * 6);
    const fret = Math.floor(Math.random() * (FRETS + 1));
    const n = noteAt(stringIdx, fret);
    setQuizTarget({ string: stringIdx, fret, note: n.name });
    setQuizFeedback(null);
  }, []);

  useEffect(() => {
    if (mode === 'quiz' && !quizTarget) newQuiz();
  }, [mode, quizTarget, newQuiz]);

  const onQuizGuess = useCallback((guess) => {
    if (!quizTarget) return;
    if (guess === quizTarget.note) {
      playNote(quizTarget.string, quizTarget.fret);
      setQuizScore((s) => s + 1);
      setQuizStreak((s) => s + 1);
      setQuizFeedback('right');
      setTimeout(newQuiz, 600);
    } else {
      setQuizStreak(0);
      setQuizFeedback('wrong');
      setTimeout(() => setQuizFeedback(null), 700);
    }
  }, [quizTarget, playNote, newQuiz]);

  // ---- reveal animation ----
  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.utils.toArray('.fret-reveal').forEach((el) => {
        gsap.from(el, {
          opacity: 0,
          y: 40,
          duration: 1,
          ease: 'power3.out',
          scrollTrigger: { trigger: el, start: 'top 88%' },
        });
      });
    }, sectionRef);
    return () => ctx.revert();
  }, []);

  // Build chord shape for visual highlight
  const chordShape = mode === 'chord' ? CHORDS[activeChord].shape : null;

  // marker frets (standard guitar dots)
  const dotFrets = [3, 5, 7, 9];
  const doubleDotFret = 12;

  return (
    <section
      id="play"
      ref={sectionRef}
      className="relative py-32 sm:py-40 bg-stage overflow-hidden"
    >
      <div className="container-x">
        <div className="grid grid-cols-12 gap-8 mb-12">
          <div className="col-span-12 md:col-span-4">
            <div className="fret-reveal eyebrow flex items-center gap-3">
              <span className="font-mono text-accent/80">[05]</span>
              <span>Off the clock</span>
              <span className="flex-1 h-px bg-white/10 ml-2" />
            </div>
          </div>
          <div className="col-span-12 md:col-span-8">
            <h2 className="fret-reveal section-title leading-[1.05]">
              I build with my hands.{' '}
              <span className="text-gradient italic font-light">
                Sometimes those hands are on six strings.
              </span>
            </h2>
            <p className="fret-reveal mt-6 text-slate-350 max-w-2xl text-lg leading-relaxed">
              A real, playable fretboard — every fret is a Karplus-Strong synthesised
              note, written from scratch in the Web Audio API. Tap a fret, strum a chord,
              or test yourself in note-quiz mode. Headphones recommended.
            </p>
          </div>
        </div>

        {/* Mode tabs */}
        <div className="fret-reveal flex flex-wrap gap-2 mb-6">
          {[
            { id: 'free',  label: 'Free play' },
            { id: 'chord', label: 'Chord shapes' },
            { id: 'quiz',  label: 'Note quiz' },
          ].map((m) => (
            <button
              key={m.id}
              type="button"
              onClick={() => setMode(m.id)}
              className={`px-4 py-2 rounded-full text-sm transition-all font-mono uppercase tracking-widest ${
                mode === m.id
                  ? 'bg-accent text-ink-950 font-medium'
                  : 'border border-white/10 text-slate-250 hover:border-accent/40'
              }`}
            >
              {m.label}
            </button>
          ))}
        </div>

        {/* Chord picker */}
        {mode === 'chord' && (
          <div className="fret-reveal mb-6 flex flex-wrap items-center gap-3">
            <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-slate-450">
              Pick a chord
            </span>
            {Object.entries(CHORDS).map(([id, c]) => (
              <button
                key={id}
                type="button"
                onClick={() => setActiveChord(id)}
                className={`px-3 py-1.5 rounded-full text-xs transition-all ${
                  activeChord === id
                    ? 'bg-accent/15 border border-accent/40 text-accent'
                    : 'border border-white/10 text-slate-250 hover:border-accent/40'
                }`}
              >
                {c.name}
              </button>
            ))}
            <button
              type="button"
              onClick={() => strum(CHORDS[activeChord].shape)}
              className="ml-auto btn-primary text-xs"
            >
              <span>Strum {activeChord} ⏎ Space</span>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M5 12h14M13 5l7 7-7 7" />
              </svg>
            </button>
          </div>
        )}

        {/* Quiz HUD */}
        {mode === 'quiz' && (
          <div className="fret-reveal mb-6 glass rounded-2xl p-5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <div className="font-mono text-[10px] tracking-[0.2em] uppercase text-slate-450 mb-1">
                What note is highlighted?
              </div>
              <div className="text-slate-150 text-lg">
                String {quizTarget ? 6 - quizTarget.string : '–'} · Fret{' '}
                {quizTarget ? quizTarget.fret : '–'}
              </div>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {NOTE_NAMES.map((n) => (
                <button
                  key={n}
                  type="button"
                  onClick={() => onQuizGuess(n)}
                  className={`w-10 h-10 rounded-lg text-sm font-mono border transition-all ${
                    quizFeedback === 'right' && n === quizTarget?.note
                      ? 'border-accent bg-accent/20 text-accent'
                      : 'border-white/10 text-slate-250 hover:border-accent/40 hover:text-accent'
                  }`}
                >
                  {n}
                </button>
              ))}
            </div>
            <div className="text-right shrink-0">
              <div className="font-display text-3xl text-slate-150 tabular-nums">
                {quizScore}
              </div>
              <div className="font-mono text-[10px] tracking-widest uppercase text-slate-450">
                streak · {quizStreak}
              </div>
            </div>
          </div>
        )}

        {/* Fretboard */}
        <div className="fret-reveal glass rounded-2xl p-4 sm:p-6 overflow-x-auto">
          <FretboardSVG
            chordShape={chordShape}
            quizTarget={mode === 'quiz' ? quizTarget : null}
            ringing={ringing}
            onPlay={playNote}
            dotFrets={dotFrets}
            doubleDotFret={doubleDotFret}
          />
          <div className="mt-3 flex items-center justify-between font-mono text-[10px] tracking-widest uppercase text-slate-450">
            <span>Standard tuning · E A D G B E</span>
            <span className="hidden sm:inline">Built with Web Audio · Karplus-Strong</span>
            <span className="sm:hidden">Web Audio</span>
          </div>
        </div>

        {/* Footer hint */}
        <p className="fret-reveal mt-6 font-mono text-[11px] text-slate-450 max-w-2xl">
          {mode === 'free' && '> Tap any fret. Lower strings sustain longer; higher strings ring brighter.'}
          {mode === 'chord' && '> Click strum or hit Space. The shape lights up — fingers go on the dots.'}
          {mode === 'quiz' && '> Pick the right note. Get them right in a row to grow the streak.'}
        </p>
      </div>
    </section>
  );
}

// ---------------- SVG fretboard render ----------------
function FretboardSVG({ chordShape, quizTarget, ringing, onPlay, dotFrets, doubleDotFret }) {
  // viewBox sized so frets get smaller as they go up (real guitar feel)
  const W = 1080;
  const H = 240;
  const padL = 64;   // open string label
  const padR = 18;
  const padT = 18;
  const padB = 28;   // fret numbers below
  const fretsW = W - padL - padR;
  const fretsH = H - padT - padB;

  // exponential fret spacing — each fret is at L * (1 - 1/2^(n/12))
  const positions = useMemo(() => {
    const total = 1 - Math.pow(0.5, FRETS / 12);
    const arr = [];
    for (let n = 0; n <= FRETS; n++) {
      const x = (1 - Math.pow(0.5, n / 12)) / total;
      arr.push(padL + x * fretsW);
    }
    return arr;
  }, [fretsW]);

  const stringYs = STRINGS.map((_, i) => padT + ((i + 0.5) * fretsH) / STRINGS.length);

  // hit-area helper — get fret center between fret n-1 and fret n
  const fretCenterX = (n) => (positions[n - 1] + positions[n]) / 2;

  // chord finger circles
  const fingers = [];
  if (chordShape) {
    chordShape.forEach((fret, sIdx) => {
      if (fret == null) return; // muted
      const cx = fret === 0 ? padL - 26 : fretCenterX(fret);
      const cy = stringYs[sIdx];
      fingers.push({ cx, cy, fret, sIdx });
    });
  }

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      width="100%"
      style={{ display: 'block', minWidth: 720 }}
      role="img"
      aria-label="Playable guitar fretboard"
    >
      <defs>
        <linearGradient id="fbWood" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0%"  stopColor="#1c1f29" />
          <stop offset="50%" stopColor="#14161e" />
          <stop offset="100%" stopColor="#0d0f15" />
        </linearGradient>
        <radialGradient id="ring" cx="50%" cy="50%" r="50%">
          <stop offset="0%"  stopColor="#7df9d4" stopOpacity="0.9" />
          <stop offset="60%" stopColor="#7df9d4" stopOpacity="0.25" />
          <stop offset="100%" stopColor="#7df9d4" stopOpacity="0" />
        </radialGradient>
      </defs>

      {/* fretboard background */}
      <rect
        x={padL - 6} y={padT - 6}
        width={fretsW + 12} height={fretsH + 12}
        rx="6"
        fill="url(#fbWood)"
        stroke="rgba(255,255,255,0.06)"
      />

      {/* inlay dots */}
      {dotFrets.map((n) => (
        <circle
          key={`dot-${n}`}
          cx={fretCenterX(n)}
          cy={padT + fretsH / 2}
          r={5}
          fill="#cdd5e1"
          fillOpacity={0.18}
        />
      ))}
      {/* double dot at fret 12 */}
      <circle cx={fretCenterX(doubleDotFret)} cy={padT + fretsH * 0.30} r={5} fill="#cdd5e1" fillOpacity={0.22} />
      <circle cx={fretCenterX(doubleDotFret)} cy={padT + fretsH * 0.70} r={5} fill="#cdd5e1" fillOpacity={0.22} />

      {/* frets (vertical lines) */}
      {positions.map((x, n) => (
        <line
          key={`fret-${n}`}
          x1={x} x2={x}
          y1={padT - 2} y2={padT + fretsH + 2}
          stroke={n === 0 ? '#cdd5e1' : 'rgba(205,213,225,0.35)'}
          strokeWidth={n === 0 ? 4 : 1.4}
        />
      ))}

      {/* fret numbers */}
      {positions.map((x, n) => (
        n > 0 && (
          <text
            key={`num-${n}`}
            x={(positions[n - 1] + positions[n]) / 2}
            y={H - 8}
            textAnchor="middle"
            fontSize="10"
            fontFamily="ui-monospace, monospace"
            letterSpacing="2"
            fill="#7d889c"
          >
            {n}
          </text>
        )
      ))}

      {/* strings */}
      {STRINGS.map((s, i) => {
        const y = stringYs[i];
        const w = 1 + i * 0.5; // thicker on lower strings
        return (
          <g key={`str-${i}`}>
            <line
              x1={padL} x2={padL + fretsW}
              y1={y} y2={y}
              stroke="#cdd5e1"
              strokeOpacity={0.55}
              strokeWidth={w}
            />
            {/* open string label */}
            <text
              x={padL - 14}
              y={y + 4}
              textAnchor="end"
              fontSize="13"
              fontFamily="ui-monospace, monospace"
              fill="#cdd5e1"
              fillOpacity={0.7}
            >
              {s.label}
            </text>
          </g>
        );
      })}

      {/* clickable fret cells */}
      {STRINGS.map((s, sIdx) => (
        <g key={`row-${sIdx}`}>
          {/* open-string clickable area to the left of fret 0 */}
          <rect
            x={padL - 40}
            y={stringYs[sIdx] - fretsH / (STRINGS.length * 2)}
            width={40}
            height={fretsH / STRINGS.length}
            fill="transparent"
            style={{ cursor: 'pointer' }}
            onClick={() => onPlay(sIdx, 0)}
          />
          {Array.from({ length: FRETS }, (_, n) => {
            const fretIdx = n + 1;
            const x1 = positions[n];
            const x2 = positions[n + 1];
            const y = stringYs[sIdx];
            const cellH = fretsH / STRINGS.length;
            const isRinging = !!ringing[`${sIdx}-${fretIdx}`];
            return (
              <g key={`cell-${sIdx}-${fretIdx}`}>
                <rect
                  x={x1}
                  y={y - cellH / 2}
                  width={x2 - x1}
                  height={cellH}
                  fill="transparent"
                  style={{ cursor: 'pointer' }}
                  onClick={() => onPlay(sIdx, fretIdx)}
                />
                {isRinging && (
                  <circle
                    cx={(x1 + x2) / 2}
                    cy={y}
                    r={Math.min(18, (x2 - x1) * 0.45)}
                    fill="url(#ring)"
                    style={{ pointerEvents: 'none' }}
                  >
                    <animate attributeName="r" from="6" to="22" dur="0.55s" fill="freeze" />
                    <animate attributeName="opacity" from="1" to="0" dur="0.55s" fill="freeze" />
                  </circle>
                )}
              </g>
            );
          })}
        </g>
      ))}

      {/* chord finger dots */}
      {fingers.map((f, i) => (
        <g key={`fg-${i}`}>
          <circle
            cx={f.cx} cy={f.cy}
            r={f.fret === 0 ? 8 : 11}
            fill={f.fret === 0 ? 'transparent' : '#7df9d4'}
            stroke="#7df9d4"
            strokeWidth={f.fret === 0 ? 2 : 0}
          />
          {f.fret > 0 && (
            <text
              x={f.cx} y={f.cy + 4}
              textAnchor="middle"
              fontSize="11"
              fontFamily="ui-monospace, monospace"
              fontWeight="600"
              fill="#0a0c12"
            >
              {f.fret}
            </text>
          )}
        </g>
      ))}

      {/* mute X marks for chord shapes */}
      {chordShape && chordShape.map((fret, sIdx) => (
        fret === null && (
          <text
            key={`mute-${sIdx}`}
            x={padL - 26}
            y={stringYs[sIdx] + 4}
            textAnchor="middle"
            fontSize="14"
            fontFamily="ui-monospace, monospace"
            fill="#ff6b6b"
            fillOpacity={0.7}
          >
            ×
          </text>
        )
      ))}

      {/* quiz target highlight */}
      {quizTarget && (
        <circle
          cx={quizTarget.fret === 0 ? padL - 26 : fretCenterX(quizTarget.fret)}
          cy={stringYs[quizTarget.string]}
          r={14}
          fill="none"
          stroke="#a78bfa"
          strokeWidth={2.5}
        >
          <animate attributeName="r" values="12;18;12" dur="1.6s" repeatCount="indefinite" />
          <animate attributeName="opacity" values="0.5;1;0.5" dur="1.6s" repeatCount="indefinite" />
        </circle>
      )}
    </svg>
  );
}
